services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-app
    volumes:
      - .:/app
    working_dir: /app
    command: sleep infinity   # 👈 clave para devcontainer
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - PYTHONUNBUFFERED=1
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama

    ports:
      - "11434:11434"

    volumes:
      - ollama_data:/root/.ollama

    restart: unless-stopped

volumes:
  ollama_data: